# Generated by Django 5.2.7 on 2025-11-01 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Телефон')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('total_orders', models.IntegerField(default=0, verbose_name='Всего заказов')),
                ('total_spent', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Всего потрачено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя сотрудника')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия сотрудника')),
                ('position', models.CharField(max_length=30, verbose_name='Должность')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Зарплата')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=50, verbose_name='Mail')),
                ('hire_date', models.DateField(verbose_name='Дата приема')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['surname', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=100, verbose_name='Название блюда')),
                ('category', models.CharField(max_length=20, verbose_name='Категория')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cooking_time', models.IntegerField(default=15, verbose_name='Время приготовления (мин)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступно')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Меню',
                'ordering': ['category', 'dish_name'],
            },
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(unique=True, verbose_name='Номер столика')),
                ('capacity', models.IntegerField(verbose_name='Вместимость')),
                ('status', models.CharField(default='free', max_length=15, verbose_name='Статус')),
                ('location', models.CharField(max_length=100, verbose_name='Расположение')),
            ],
            options={
                'verbose_name': 'Столик',
                'verbose_name_plural': 'Столики',
                'ordering': ['table_number'],
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(verbose_name='Дата заказа')),
                ('status', models.CharField(choices=[('pending', 'Принят'), ('preparing', 'Готовится'), ('ready', 'Готов'), ('served', 'Подано'), ('paid', 'Оплачен'), ('cancelled', 'Отменен')], max_length=15, verbose_name='Статус')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая сумма')),
                ('notes', models.TextField(verbose_name='Примечания')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.customers', verbose_name='Клиент')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.employees', verbose_name='Сотрудник')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.tables', verbose_name='Столик')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за единицу')),
                ('special_requests', models.TextField(verbose_name='Особые пожелания')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.menu', verbose_name='Блюдо')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='web_app.orders', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказов',
            },
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('reservation_date', models.DateTimeField(verbose_name='Дата бронирования')),
                ('guests_count', models.IntegerField(verbose_name='Количество гостей')),
                ('status', models.CharField(choices=[('confirmed', 'Подтверждено'), ('pending', 'Ожидание'), ('cancelled', 'Отменено'), ('completed', 'Завершено')], max_length=15, verbose_name='Статус')),
                ('duration', models.IntegerField(default=120, verbose_name='Продолжительность (мин)')),
                ('notes', models.TextField(verbose_name='Примечания')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.tables', verbose_name='Столик')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['reservation_date'],
            },
        ),
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField(verbose_name='Дата смены')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Отработано часов')),
                ('notes', models.TextField(verbose_name='Заметки')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='web_app.employees', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
                'ordering': ['-shift_date', 'start_time'],
                'unique_together': {('employee', 'shift_date')},
            },
        ),
    ]
