# Generated by Django 5.2.8 on 2025-11-18 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={'ordering': ['-created_at'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='employees',
            options={'ordering': ['surname', 'name'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['category', 'dish_name'], 'verbose_name': 'Dish', 'verbose_name_plural': 'Menu'},
        ),
        migrations.AlterModelOptions(
            name='orderitems',
            options={'verbose_name': 'Order item', 'verbose_name_plural': 'Order item'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['-order_date'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='reservations',
            options={'ordering': ['reservation_date'], 'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservations'},
        ),
        migrations.AlterModelOptions(
            name='shifts',
            options={'ordering': ['-shift_date', 'start_time'], 'verbose_name': 'Shift', 'verbose_name_plural': 'Shifts'},
        ),
        migrations.AlterModelOptions(
            name='tables',
            options={'ordering': ['table_number'], 'verbose_name': 'Table', 'verbose_name_plural': 'Tables'},
        ),
        migrations.AddField(
            model_name='menu',
            name='image_name',
            field=models.CharField(default='default.jpg', max_length=100, verbose_name='Image filename'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Registration date'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='total_orders',
            field=models.IntegerField(default=0, verbose_name='Total orders'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total spent'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='hire_date',
            field=models.DateField(verbose_name='Hire date'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Employee name'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='position',
            field=models.CharField(max_length=30, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='surname',
            field=models.CharField(max_length=30, verbose_name='Employee surname'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='cooking_time',
            field=models.IntegerField(default=15, verbose_name='Cooking time (min)'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='dish_name',
            field=models.CharField(max_length=100, verbose_name='Dish name'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Available'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.menu', verbose_name='Dish'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='web_app.orders', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price per unit'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='special_requests',
            field=models.TextField(verbose_name='Special request'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.customers', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.employees', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='notes',
            field=models.TextField(verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(verbose_name='Order date'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('served', 'Served'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.tables', verbose_name='Table'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total price'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='customer_name',
            field=models.CharField(max_length=100, verbose_name='Customer name'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='duration',
            field=models.IntegerField(default=120, verbose_name='Duration (min)'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='guests_count',
            field=models.IntegerField(verbose_name='Guests count'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='notes',
            field=models.TextField(verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='reservation_date',
            field=models.DateTimeField(verbose_name='Reservation date'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.tables', verbose_name='Table'),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='web_app.employees', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='end_time',
            field=models.TimeField(verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Hours worked'),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='notes',
            field=models.TextField(verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='shift_date',
            field=models.DateField(verbose_name='Shift date'),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='start_time',
            field=models.TimeField(verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='capacity',
            field=models.IntegerField(verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='status',
            field=models.CharField(default='free', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='table_number',
            field=models.IntegerField(unique=True, verbose_name='Table number'),
        ),
    ]
